### ISSUE TITLE
Supported configuration file extension check does not use the per-generator default

### ISSUE THREAD

**Issue by haykam821** [actions/configure-pages#104]
The `setPagesConfig` function uses different error messages depending on whether the generator configuration file has a correct extension. However, the configuration file used for this check is based on the context `generator_config_file` input only, rather than the default configuration file for the generator used that is computed by the `getConfigParserSettings` function.

As a result, if `generator_config_file` is not specified, then errors within the `setPagesConfig` function will always be blamed on an incorrect file extension.

**Comment by janbrasna** [comment]
Basically the check:

https://github.com/actions/configure-pages/blob/b490f538fb047e8461be7770e7347f9c197aeddc/src/set-pages-config.js#L80-L90

should return `isSupportedFileExtension` true if `!generatorConfigFile` and that's all I guess.

 _(It would be better to use `settings.configurationFile` output instead that should have the template config path filled in if no passed config, but that's another scope and the actual getter might have thrown so no point getting the output again, oh well…)_

So maybe just something like:

```diff
--- a/src/set-pages-config.js
+++ b/src/set-pages-config.js
@@ -76,12 +78,12 @@ function setPagesConfig({ staticSiteGenerator, generatorConfigFile, siteUrl }) {
     const settings = getConfigParserSettings({ staticSiteGenerator, generatorConfigFile, siteUrl })
     new ConfigParser(settings).injectAll()
   } catch (error) {
-    const isSupportedFileExtension = SUPPORTED_FILE_EXTENSIONS.some(ext => generatorConfigFile.endsWith(ext))
+    const isSupportedFileExtension = !generatorConfigFile || SUPPORTED_FILE_EXTENSIONS.some(ext => generatorConfigFile.endsWith(ext))
 
     // Logging
     if (!isSupportedFileExtension) {
```

**Comment by JamesMGreene** [comment]
I believe the main problem here (our failure to log the actual error message) is resolved by:
- https://github.com/actions/configure-pages/pull/138

As for failure to correctly detect config files, I'm going to leave that in another issue:
- https://github.com/actions/configure-pages/issues/107

**Comment by janbrasna** [comment]
@JamesMGreene Thanks for keeping this in mind. The issue here is different than the referenced autodetection. To quote the important bit:

> " if `generator_config_file` is not specified, then errors within the `setPagesConfig` function will always be blamed on an incorrect file extension."

To simplify, if you don't pass any config file and the action uses its own implicit boilerplate, the conditional logic testing whether to log "We were unable to determine…" or "Unsupported configuration file extension…" fails because https://github.com/actions/configure-pages/blob/fc47e3c8386fa64ae7a2419b64710d432c7a3b90/src/set-pages-config.js#L85 this doesn't work for when there's no config specified, as `generatorConfigFile.endsWith(ext)` is empty/falsy, so it "seems" that all errors are then blamed on extension, when that isn't the case if you're not providing a config at all;)

It's just cosmetics though.

**Comment by janbrasna** [comment]
No worries;) I'd have already demonstrated it better by proposing a fix just by adding the _const isSupportedFileExtension = **!generatorConfigFile ||** SUPPORTED_FILE_EXTENSIONS.some…_ to avoid blaming any errors without config file present on its extension straight away, however TBH I lack the imagination to properly test such change esp. in edge case error handler and not to introduce any potential surface for more issues stemming from it so I leave that to others… I see you've taken more systematic approach to the whole configs magic so I'm just watching from the passenger seat: Good job! 🎩

**Comment by JamesMGreene** [comment]
A fix for this is now included in `actions/configure-pages@v5`. 🚀
