### ISSUE TITLE
Set `$BASE_URL` or similar env var for subsequent steps

### ISSUE THREAD

**Issue by jcbhmr** [actions/configure-pages#105]
It's my understanding that this action is sort of an optional configuration step in the chain of:
- actions/configure-pages
- (build your site)
- actions/upload-pages-artifact
- actions/deploy-pages

Where actions/configure-pages is supposed to tweak some configs a bit like for Next.js to make it play nice with a `https://example.org/sub-project/...` base URL.

Since that seems to be the goal, I'd like to propose a feature: auto-setting some kind of `$PAGES_BASE_URL` or `$BASE_URL` (idk if there's a common conventional name or standard) or some other environment variable like this:

```js
await appendFile(process.env.GITHUB_ENV, `BASE_URL=${baseURL}`)
// or similar
```

Why is this a good idea? **1)** It's an **environment variable**, not an output. That means you don't need to do this messiness each time you want to use it:
```yml
- id: my-id
  uses: actions/configure-pages@vN
- run: npm run build:docs
  env:
    BASE_URL: ${{ steps.my-id.outputs.base_url }}/
```

**2)** It makes it much easier for non-Next.js/Jekyll/whatever supported projects in [the magic js file](https://github.com/actions/configure-pages/blob/main/src/set-pages-config.js) to just pick up on a `$BASE_URL` env var. Yes, you can do this now but it's a bit clunky with adding the outputs to an env var manually.

**This proposed `$BASE_URL` idea is more _implicit_** than the current explicit `${{ steps.my-id.outputs.base_url }}` is right now. In my opinion that's OK similar to how there's already a slew of `$GITHUB_*` env vars but my opinion isn't the right answer.

If this is out-of-scope, feel free to close this. This is just a QoL feature that would make it easier to do configs without mucking with outputs in `my-pages-workflow.yml`. 🤷‍♀️

**Comment by jcbhmr** [comment]
This would also be a way around issues like https://github.com/actions/configure-pages/issues/74 so that you can just do something like this in your config as opposed to wrangling with manually computing `process.env.GITHUB_REPOSITORY.split("/")[1]` and handling `if (process.env.GITHUB_REPOSITORY.split("/")[1].endsWith(".github.io")) ...` edge cases

```js
module.exports = {
  ...process.env.BASE_URL && { basePath: new URL(process.env.BASE_URL).pathname },
}
```

**Comment by JamesMGreene** [comment]
`BASE_URL` is a far too generic environment variable name for GitHub Pages to lay claim to. If we were going to do something like this, it would be very explicitly named, like `GITHUB_PAGES_BASE_URL`.

As it is, I would still suggest utilizing the action's `outputs.base_url` to set the value of the relevant environment variable for your own usage as outlined in your original post. 🤷
