### ISSUE TITLE
Doesn't recognize next.config.mjs

### ISSUE THREAD

**Issue by pratv1** [actions/configure-pages#107]
It works fine with the `js` extension:

```
Run actions/configure-pages@v3
  with:
    static_site_generator: next
Injecting property=basePath and value= in:
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
};
```

...but when I have a `next.config.mjs`, it ignores it and makes up a new config file on its own:

```
Run actions/configure-pages@v3
  with:
    static_site_generator: next
Using default blank configuration
Injecting property=basePath and value= in:
// Default Pages configuration for Next
const nextConfig = {}
module.exports = nextConfig
```

**Comment by 2chanhaeng** [comment]
I had a similar problem to yours for a similar reason.
Recently, when I create a project with `create-next-app`, it generates `next.config.mjs` instead of `next.config.js`.
So I think this issue could be going bigger and should be fixed sooner rather than later.
Additionally, I temporarily fixed the issue by deleting `next.config.js` just before the build:
```yaml

**Comment by OtmaniCodes** [comment]
is a solution found to this issue?

**Comment by pratv1** [comment]
@OtmaniCodes I ended up commenting out this line from the build step to make it work:

![image](https://github.com/actions/configure-pages/assets/7577656/269d0dda-cc89-41c9-8d45-9c9b3dd219be)

You can check my [workflow file](https://github.com/pratv1/pratv1.github.io/blob/main/.github/workflows/nextjs.yml) for reference.

**Comment by OtmaniCodes** [comment]
> @OtmaniCodes I ended up commenting out this line from the build step to make it work:
> 
> ![image](https://private-user-images.githubusercontent.com/7577656/313486705-269d0dda-cc89-41c9-8d45-9c9b3dd219be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTE4NjEsIm5iZiI6MTcxMDY5MTU2MSwicGF0aCI6Ii83NTc3NjU2LzMxMzQ4NjcwNS0yNjlkMGRkYS1jYzg5LTQxYzktOGQ0NS05YzliM2RkMjE5YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTdUMTYwNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY0OTEyMjU0ZDY4Y2ZjMGRkNTA2YTU4MDJmYzM1ZGRkYzg2YjA5YzcyMzE4NDNkZDNiMjViMGU0NWMzYzg2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XjQ8brrEJN-upVPK8aXn_kWRqyOzxaObdijMK5FFzNU)
> 
> You can check my [workflow file](https://github.com/pratv1/pratv1.github.io/blob/main/.github/workflows/nextjs.yml) for reference.

Thank you

**Comment by JamesMGreene** [comment]
The available workaround is to provide the path in your Actions workflow via the `generator_config_file` input parameter, e.g.:

```yaml
- name: Setup Pages
  uses: actions/configure-pages@v3
  with:
    static_site_generator: next
    generator_config_file: ./next.config.mjs
```

For now, I'll leave this issue open to look at auto-detecting alternative file paths. It's not something we'd prioritize highly, but it isn't an unreasonable expectation given the behind-the-scenes magic this action is already attempting to take care of on users' behalf. 🤷

**Comment by JamesMGreene** [comment]
A fix for this is now included in `actions/configure-pages@v5`. 🚀

**Comment by imbirdperson** [comment]
I'm still getting the error after tyring all the above solutions. I'm new to JavaScript world. Can some one help me identify the problem. Below is the github action error. But I'm able to build the page locally without any errors. 

'''Run actions/configure-pages@v5
Injecting property=output and value=export in:
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const withMDX = require('@next/mdx')({
  extension: /\.mdx?$/,
});

/** @type {import('next').NextConfig} */
const nextConfig = {
    output:'export',
    distDir:'dist',
    images:{
        unoptimized: true,
    },

    pageExtensions: ['js', 'jsx', 'mdx', 'ts', 'tsx'],

};

export default withMDX(nextConfig);

Error: TypeError: error must be an instance of Error'''

**Comment by richardtorres314** [comment]
> A fix for this is now included in `actions/configure-pages@v5`. 🚀
> 
> e.g.
> 
> ```yaml
> - name: Setup Pages
>   uses: actions/configure-pages@v5
>   with:
>     static_site_generator: next
> ```

@JamesMGreene The fix works well when there's no import, but seems to break when importing a dependency (or at least the `@next/bundle-analyzer` as I've tried). For example, in a `next.config.mjs` file:

```JavaScript
// @ts-check

import NextBundleAnalyzer from '@next/bundle-analyzer';

const withBundleAnalyzer = NextBundleAnalyzer({
  enabled: process.env.ANALYZE === "true",
});

/** @type {import('next').NextConfig} */
const nextConfig = {
 output: "export"
};

export default withBundleAnalyzer(nextConfig);
```

results in the `configure-pages` action erroring out with the message, "TypeError: error must be an instance of Error".

Commenting the `static_site_generator: next` line seems to resolve the type error.

A minor inconvenience, but a workaround suffices. Glad to see the project continued adoption!

**Comment by ashrielbrian** [comment]
Can echo @richardtorres314 on breaking when there's an import. Mine fails when I use an import as such:

```tsx
import nextMDX from "@next/mdx";

const withMDX = nextMDX();

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Configure `pageExtensions` to include MDX files
  pageExtensions: ["js", "jsx", "mdx", "ts", "tsx"]
};

export default withMDX(nextConfig);
```

**Comment by staceysych23** [comment]
@ashrielbrian have you resolved the issue?

**Comment by ashrielbrian** [comment]
@staceysych23 yeah, i uncommented all the options for the GH action. This suffices:

```
      - name: Setup Pages
        uses: actions/configure-pages@v5
```
