### ISSUE TITLE
Major v5

### ISSUE THREAD

**Issue by TWiStErRob** [actions/configure-pages#140]
https://github.com/actions/configure-pages/releases/tag/v5.0.0 does not have enough information.

When an automated upgrade PR (e.g. Dependabot / Renovate) is opened, it uses the release info.

Please clarify why v5 is a breaking change and what migration steps we need to take.

**Comment by TWiStErRob** [comment]
@JamesMGreene

**Comment by JamesMGreene** [comment]
Thanks the callout! I definitely had included breaking change information in the draft, but I'm assuming the release drafting automation overwrote it. 🙈 

I'll get that updated today.

**Comment by JamesMGreene** [comment]
The [release notes for `v5.0.0`](https://github.com/actions/configure-pages/releases/tag/v5.0.0) have been updated to include a "Breaking Changes" section.

Key content added there:

# Breaking Changes

:warning: This version contains breaking changes! :warning:

- When using the [input param `static_site_generator: next`](https://github.com/actions/configure-pages/blob/983d7736d9b0ae728b81ab479565c72886d7745b/action.yml#L7-L10):
  - Added support for Next.js >= 13.3.0
  - Consequently, also dropped support for Next.js < 13.3.0

**Comment by TWiStErRob** [comment]
Thanks for re-adding it!
