### ISSUE TITLE
Error when trying to build for NextJS 12.3

### ISSUE THREAD

**Issue by bobeagan** [actions/configure-pages#23]
The current injection for the default template causes a failure due to specifying the unoptimized value for images to be wrapped in an experimental block. `const nextConfig = {experimental: {images: {unoptimized: true}},basePath: "/test"}`

However, as of 12.3 this is no longer necessary and will cause build failure of:
> Error: Image Optimization using Next.js' default loader is not compatible with `next export`.

Workaround is to explicitly set the correct value in the next.config.js. Suggesting to either determine version or allow it to be specified in order to conditionally apply the experimental wrapper.

Source:  https://nextjs.org/blog/next-12-3#disable-image-optimization-stable

**Comment by TheKojuEffect** [comment]
Here's a PR for this issue: https://github.com/actions/configure-pages/pull/33

**Comment by JamesMGreene** [comment]
Fixed by #33 / #37
