### ISSUE TITLE
Pages config is not injected when generators using with typescript

### ISSUE THREAD

**Issue by bicstone** [actions/configure-pages#28]
Pages config is not injected when using [gatsby-config.ts](https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#gatsby-configts).
Gatsby will ignore pathPrefix and build the site as if hosted from the root domain.

**To Reproduce**

1. [Create Gatsby Project with TypeScript](https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#initializing-a-new-project-with-typescript)
2. [Add deploy action from template](https://github.com/bicstone/temp-gatsby-starter-ts/blob/0154cee6a436af6838fdd9ccda03c558e52c2756/.github/workflows/gatsby.yml)
3. [Run Workflow](https://github.com/bicstone/temp-gatsby-starter-ts/actions/runs/3134901820/jobs/5089975040#step:5:1)

Run actions/configure-pages@v2

```
Using default blank configuration
Injecting property=pathPrefix and value=/temp-gatsby-starter-ts/ in:
// Default Pages configuration for Gatsby
module.exports = {}

Found configuration object in direct module export
Injection successful, new configuration:
// Default Pages configuration for Gatsby
module.exports = {pathPrefix: "/temp-gatsby-starter-ts/"}

Injecting property=siteMetadata.siteUrl and value=https://bicstone.github.io/ in:
// Default Pages configuration for Gatsby
module.exports = {pathPrefix: "/temp-gatsby-starter-ts/"}

Found configuration object in direct module export
Injection successful, new configuration:
// Default Pages configuration for Gatsby
module.exports = {siteMetadata: {siteUrl: "https://bicstone.github.io/"},pathPrefix: "/temp-gatsby-starter-ts/"}
```

<img src="https://user-images.githubusercontent.com/47806818/192507737-f6228c0a-dea5-47fb-b158-e26e6b4259d8.png" width="600" alt="Gatsby will ignore pathPrefix and build the site as if hosted from the root domain" />

https://bicstone.github.io/temp-gatsby-starter-ts/

**Comment by yoannchaudet** [comment]
👋 `actions/configure-pages` does not support or understand TypeScript today. And it is really hard to support all the things when a language parser is required.

You probably want to configure Pages manually yourself in this case since you are a bit out of the "default" paths.

**Comment by bicstone** [comment]
Thank you for your reply!
`gatsby-config.ts` is configured in the Gatsby official starter, although it is out of the default.
https://github.com/gatsbyjs/gatsby/tree/gatsby%404.24.0/starters/gatsby-starter-minimal-ts

It would be nice if you could be able to warn that extensions other than `.js, ,.cjs, .mjs` are not supported if specified in generator_config_file.

#29
