### ISSUE TITLE
Showing warning `'set-output' command is deprecated`

### ISSUE THREAD

**Issue by arifszn** [actions/configure-pages#32]
While using this workflow, it is showing warning:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Full log: https://github.com/arifszn/gitprofile/actions/runs/3306031156/jobs/5456613147#step:4:7

**Comment by yoannchaudet** [comment]
We had forgotten to release https://github.com/actions/configure-pages/releases/tag/v2.1.2.

Now that it is done, you should be all good.

Let us know if that's not the case!
