### ISSUE TITLE
Incorrect link "all code changes" for v3.0.0 release

### ISSUE THREAD

**Issue by ivan-magda** [actions/configure-pages#49]
[Release v3.0.0](https://github.com/actions/configure-pages/releases/tag/v3.0.0) has an incorrect link for "all code changes". Needs to be updated from https://github.com/actions/configure-pages/compare/v2.1.3...v2.1.4 to https://github.com/actions/configure-pages/compare/v2.1.3...v3.0.0

**Comment by yoannchaudet** [comment]
Thank you, fixed!
