### ISSUE TITLE
Support for specifying folder

### ISSUE THREAD

**Issue by karl-run** [actions/configure-pages#5]
My next project is in a monorepo, and therefore the `next.config.js` isn't on root.

An input so I could specify the working directory would solve this for me.

**Comment by JamesMGreene** [comment]
This is a good idea, though I think we would benefit more users if we allow the configuration file path to be specified rather than just the parent directory. That way, we can easily cover alternative file names and extensions (e.g. `*.js`, `*.cjs`, `*.mjs`).

**Comment by JamesMGreene** [comment]
@karl-run Here's a PR if you want to give it a try: https://github.com/actions/configure-pages/pull/15
