### ISSUE TITLE
Proxy issues when using self-hosted runners

### ISSUE THREAD

**Issue by jeremy-daley-kr** [actions/configure-pages#64]
I've run into issues with this action and the deploy-pages action because they don't seem to support proxies in self-hosted runners. It's not a 404, rather a 400:

![image](https://user-images.githubusercontent.com/77355440/218040049-3c264c0c-c9f8-466e-a2a4-f429151b8a83.png)

Please consider this PR: https://github.com/actions/configure-pages/pull/63
It uses the `@actions/github` API instead of manually constructing the `axios` requests. Whatever their package is doing behind the scenes fixes the self-hosted runner issue I'm having... and honestly just makes more sense in my opinion.

**Comment by JamesMGreene** [comment]
Fixed by PR #63 (thanks to you! 💝)
